name: 'telco_churn'
version: '1.0.0'
config-version: 2

profile: 'telco_churn'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  telco_churn:
    materialized: view